name: Import Project

description: 'Import settings and configurations and apply them to a Descope project'

author: 'Descope'

branding:
  icon: 'database'
  color: 'green'

inputs:
  project_id:
    description: 'The id of the Descope project to import into'
    required: true
  management_key:
    description: 'The management key for the Descope project'
    required: true
  files_path:
    description: 'The path to the import files (i.e., the directory containing the environment.json file)'
    default: '.'
  descopecli_version:
    description: 'The version of the descopecli tool to use'
    default: 'v0.1.0'
  descope_base_url:
    description: 'The base URL used to communicate with Descope servers (for troubleshooting purposes)'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Cache Descopecli
      id: cache-action
      uses: actions/cache@v4
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-descopecli-${{ inputs.descopecli_version }}

    - name: Install Descopecli
      if: steps.cache-action.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/descope/descopecli@main

    - name: Validate State
      shell: bash
      run: |
        echo "Validating action state"
        if [ -z "${{ inputs.project_id }}" ]; then
          echo "The project_id input is required for this action to run"
          exit 1
        fi
        MANAGEMENT_KEY="$(jq -r '.inputs.management_key' $GITHUB_EVENT_PATH)"
        echo ::add-mask::$MANAGEMENT_KEY
        if [ -z "$MANAGEMENT_KEY" ]; then
          echo "The management_key input is required for this action to run"
          exit 1
        fi
        if [ -z "${{ inputs.files_path }}" ]; then
          echo "The files_path input is cannot be an empty string"
          exit 1
        fi
        if ! [ -d "${{ inputs.files_path }}" ]; then
          echo "The files_path input '${{ inputs.files_path }}' doesn't exist, make sure the checkout action was called"
          exit 1
        fi

    - name: Import Project
      shell: bash
      env:
        DESCOPE_MANAGEMENT_KEY: ${{ inputs.management_key }}
        DESCOPE_BASE_URL: ${{ inputs.descope_base_url }}
      run: |
        echo "Importing project"
        descopecli project import "${{ inputs.project_id }}" --path "${{ inputs.files_path }}"
