name: Import Project

description: 'Import settings and configurations and apply them to a Descope project'

author: 'Descope'

branding:
  icon: 'database'
  color: 'green'

inputs:
  project_id:
    description: 'The id of the Descope project to import into'
    required: true
  management_key:
    description: 'The management key for the Descope project'
    required: true
  secrets:
    description: 'An optional JSON value with additional secrets to inject into the import data'
    default: '[]'
  files_path:
    description: 'The path to the import files (i.e., the directory containing the environment.json file)'
    default: '.'
  validate_only:
    description: 'Whether to only perform the validate step'
    type: boolean
  import_only:
    description: 'Whether to only perform the import step'
    type: boolean
  descopecli_version:
    description: 'The version of the descopecli tool to use'
    default: 'v0.1.0'
  descope_base_url:
    description: 'The base URL used to communicate with Descope servers (for troubleshooting purposes)'

outputs:
  failure_file:
    description: 'The path to a file with a list of failures, or empty if there were none'
    value: ${{ steps.validate.outputs.failures_file }}
  secrets_file:
    description: 'The path to a JSON array with any missing secrets, or empty if there were none'
    value: ${{ steps.validate.outputs.secrets_file }}

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    - name: Cache Descopecli
      id: cache-action
      uses: actions/cache@v4
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-descopecli-${{ inputs.descopecli_version }}

    - name: Install Descopecli
      if: steps.cache-action.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/descope/descopecli@validate-import

    - name: Check State
      shell: bash
      run: |
        echo "Checking action state"
        if [ -z "${{ inputs.project_id }}" ]; then
          echo "The project_id input is required for this action to run"
          exit 1
        fi
        MANAGEMENT_KEY="$(jq -r '.inputs.management_key' $GITHUB_EVENT_PATH)"
        echo ::add-mask::$MANAGEMENT_KEY
        if [ -z "$MANAGEMENT_KEY" ]; then
          echo "The management_key input is required for this action to run"
          exit 1
        fi
        if [ -z "${{ inputs.files_path }}" ]; then
          echo "The files_path input cannot be an empty string"
          exit 1
        fi
        if ! [ -d "${{ inputs.files_path }}" ]; then
          echo "The files_path input '${{ inputs.files_path }}' doesn't exist, make sure the checkout action was called"
          exit 1
        fi

    - name: Validate Data
      if: ${{ !inputs.import_only }}
      id: validate
      shell: bash
      env:
        DESCOPE_MANAGEMENT_KEY: ${{ inputs.management_key }}
        DESCOPE_BASE_URL: ${{ inputs.descope_base_url }}
      run: |
        echo "Validating project data"
        set +e
        SECRETS_INPUT="$(mktemp)"
        SECRETS_OUTPUT="$(mktemp)"
        FAILURE_OUTPUT="$(mktemp)"
        jq -r '.inputs.secrets' $GITHUB_EVENT_PATH > "$SECRETS_INPUT"
        descopecli project validate "${{ inputs.project_id }}" --path "${{ inputs.files_path }}" --secrets-input "$SECRETS_INPUT" --secrets-output "$SECRETS_OUTPUT" --failure-output "$FAILURE_OUTPUT"
        result=$?
        rm "$SECRETS_INPUT"
        if [ "$result" = "2" ]; then
          if [ -f "$SECRETS_OUTPUT" ] && [ -s "$SECRETS_OUTPUT" ]; then
            echo secrets_file="$SECRETS_OUTPUT" >> $GITHUB_OUTPUT
          fi
          if [ -f "$FAILURE_OUTPUT" ] && [ -s "$FAILURE_OUTPUT" ]; then
            echo failure_file="$FAILURE_OUTPUT" >> $GITHUB_OUTPUT
          fi
        fi
        exit $result

    - name: Import Project
      if: ${{ !inputs.validate_only }}
      shell: bash
      env:
        DESCOPE_MANAGEMENT_KEY: ${{ inputs.management_key }}
        DESCOPE_BASE_URL: ${{ inputs.descope_base_url }}
      run: |
        echo "Importing project"
        set +e
        SECRETS_INPUT="$(mktemp)"
        jq -r '.inputs.secrets' $GITHUB_EVENT_PATH > "$SECRETS_INPUT"
        descopecli project import "${{ inputs.project_id }}" --path "${{ inputs.files_path }}" --secrets-input "$SECRETS_INPUT"
        result=$?
        rm "$SECRETS_INPUT"
        exit $result
