name: Run Linter

description: Run Linter

inputs:
  go_version:
    description: 'Version of Go to use for this build'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Repo
      uses: ./.github/actions/ci/setup
      with:
        go_version: ${{ inputs.go_version }}

    - name: Run Linter
      uses: golangci/golangci-lint-action@2e788936b09dd82dc280e845628a40d2ba6b204c # v6.3.1
      with:
        version: v1.61.0
        skip-pkg-cache: true
        skip-build-cache: true
        args: --config=.github/actions/ci/lint/golangci.yml
