name: Run Linter

description: Run Linter

inputs:
  go_version_file:
    description: 'Path to go.mod file for determining Go version'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Repo
      uses: ./.github/actions/ci/setup
      with:
        go_version_file: ${{ inputs.go_version_file }}

    - name: Run Linter
      uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
      with:
        # renovate: datasource=github-releases depName=golangci/golangci-lint
        version: v2.11.4
        args: --config=.github/actions/ci/lint/golangci.yml
