name: Setup Repo

description: Setup Repo

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      env:
        TAR_OPTIONS: --skip-old-files
      with:
        cache: true
        go-version-file: go.mod
