name: Setup Repo

description: Setup Repo

inputs:
  go_version:
    description: 'Version of Go to use for this build'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ inputs.go_version }}
        cache: false

    - name: Enable Cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
