name: Setup Repo

description: Setup Repo

inputs:
  go_version_file:
    description: 'Path to go.mod file for determining Go version'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: ${{ inputs.go_version_file }}
        cache: false

    - name: Enable Cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
