name: Setup Repo

description: Setup Repo

inputs:
  go_version:
    description: 'Version of Go to use for this build'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: ${{ inputs.go_version }}
        cache: false

    - name: Enable Cache
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
