name: Setup Repo

description: Setup Repo

inputs:
  go_version:
    description: 'Version of Go to use for this build'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
      with:
        go-version: ${{ inputs.go_version }}
        cache: false

    - name: Enable Cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
