name: Install Descope CLI

description: 'Installs the Descope CLI tool'

author: 'Descope'

inputs:
  version:
    description: 'The version of the descope CLI tool to use'
    default: 'v0.8.13'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: '1.24'
        cache: false

    - name: Cache Descopecli
      id: cache-cli
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        path: ~/go/bin/descopecli
        key: ${{ runner.os }}-descopecli-${{ inputs.version }}

    - name: Install Descopecli
      if: steps.cache-cli.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/descope/descopecli@${{ inputs.version }}

    - name: Copy Renamed
      shell: bash
      run: cp ~/go/bin/descopecli ~/go/bin/descope
