name: Install Descope CLI

description: 'Installs the Descope CLI tool'

author: 'Descope'

inputs:
  version:
    description: 'The version of the descope CLI tool to use'
    default: 'v0.8.13'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: '1.24'
        cache: false

    - name: Cache Descopecli
      id: cache-cli
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/go/bin/descopecli
        key: ${{ runner.os }}-descopecli-${{ inputs.version }}

    - name: Install Descopecli
      if: steps.cache-cli.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/descope/descopecli@${{ inputs.version }}

    - name: Copy Renamed
      shell: bash
      run: cp ~/go/bin/descopecli ~/go/bin/descope
