name: Install Descope CLI

description: 'Installs the Descope CLI tool'

author: 'Descope'

inputs:
  version:
    description: 'The version of the descope CLI tool to use'
    default: 'v0.8.13'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
      with:
        go-version: '1.25'
        cache: false

    - name: Cache Descopecli
      id: cache-cli
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/go/bin/descopecli
        key: ${{ runner.os }}-descopecli-${{ inputs.version }}

    - name: Install Descopecli
      if: steps.cache-cli.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/descope/descopecli@${{ inputs.version }}

    - name: Copy Renamed
      shell: bash
      run: cp ~/go/bin/descopecli ~/go/bin/descope
