name: Install Descope CLI

description: "Installs the Descope CLI tool"

author: "Descope"

inputs:
  version:
    description: "The version of the descope CLI tool to use"
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        cache: true

    - name: Cache Descopecli
      id: cache-cli
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
      with:
        path: ~/go/bin/descopecli
        key: ${{ runner.os }}-descopecli-${{ inputs.version }}

    - name: Install Descopecli
      if: steps.cache-cli.outputs.cache-hit != 'true'
      shell: bash
      run: go install github.com/descope/descopecli@${{ inputs.version }}

    - name: Copy Renamed
      shell: bash
      run: cp ~/go/bin/descopecli ~/go/bin/descope
