name: Release
on:
  pull_request:
  push:
    tags:
      - v*.*.*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    permissions:
      contents: write
      id-token: write
      packages: write
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003 # v4.1.1
        with:
          cosign-release: v3.0.5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          install-only: true
          version: v2.14.3
      - name: Run GoReleaser on tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          goreleaser release --clean
        env:
          QUILL_NOTARY_ISSUER: ${{ secrets.QUILL_NOTARY_ISSUER }}
          QUILL_NOTARY_KEY: ${{ secrets.QUILL_NOTARY_KEY }}
          QUILL_NOTARY_KEY_ID: ${{ secrets.QUILL_NOTARY_KEY_ID }}
          QUILL_SIGN_P12: ${{ secrets.QUILL_SIGN_P12 }}
          QUILL_SIGN_PASSWORD: ${{ secrets.QUILL_SIGN_PASSWORD }}
      - name: Run GoReleaser on PR
        if: github.event_name == 'pull_request'
        env:
          QUILL_NOTARY_ISSUER: ${{ secrets.QUILL_NOTARY_ISSUER }}
          QUILL_NOTARY_KEY: ${{ secrets.QUILL_NOTARY_KEY }}
          QUILL_NOTARY_KEY_ID: ${{ secrets.QUILL_NOTARY_KEY_ID }}
          QUILL_SIGN_P12: ${{ secrets.QUILL_SIGN_P12 }}
          QUILL_SIGN_PASSWORD: ${{ secrets.QUILL_SIGN_PASSWORD }}
        run: |
          goreleaser release --snapshot --clean
      - name: Upload artifacts
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: release
          path: dist/*

  packages:
    permissions:
      contents: read
      packages: write
    needs: publish
    concurrency:
      group: "packages"
      cancel-in-progress: false # we want to avoid conflicts in git push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Packages Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: descope/packages
          ssh-key: ${{ secrets.PACKAGES_DEPLOY_KEY }}
          path: packages
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: release
          path: dist
      - name: Install Aptly and Createrepo
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A0546A43624A8331
          echo "deb http://repo.aptly.info/ squeeze main" | sudo tee /etc/apt/sources.list.d/aptly.list
          sudo apt-get update
          sudo apt-get install -y aptly ca-certificates createrepo-c rsync
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        id: gpg
        with:
          gpg_private_key: ${{ secrets.MAVEN_GPG_KEY }}
          passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      - name: Update APT repository
        run: |
          # Create a new repository
          aptly repo create -distribution=stable -component=main descope

          # add the contents of the current repository to the new one
          aptly repo add descope packages/

          # add the new dist packages
          aptly repo add descope dist/

          # publish it
          aptly publish repo descope
          rsync -r ~/.aptly/public/* ./packages
      - name: Update yum repository
        run: |
          echo "%_gpg_name ${{ steps.gpg.outputs.name }} <${{ steps.gpg.outputs.email}}>" > ~/.rpmmacros
          rpmsign --addsign dist/*.rpm
          rsync -r dist/*.rpm ./packages
          createrepo_c packages
          find packages
          gpg --yes --detach-sign --armor packages/repodata/repomd.xml
      - name: Commit and push changes
        working-directory: packages
        run: |
          git config --global user.email "devops+pkgs@descope.com"
          git config --global user.name "Descope DevOps"
          git add -A .
          git commit -m "Update packages from ${{ github.repository }}@${{ github.ref }}"
          git push
